/*
* This file is part of the Factbook Generator.
*
* The Factbook Generator is free software: you can redistribute it and/or modify
* it under the terms of the GNU General Public License as published by
* the Free Software Foundation, either version 3 of the License, or
* (at your option) any later version.
*
* The Factbook Generator is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
*
* You should have received a copy of the GNU General Public License
* along with The Factbook Generator.  If not, see <http://www.gnu.org/licenses/>.
*
* Copyright 2008, 2009 Bradley Brown, Dustin Yourstone, Jeffrey Hair, Paul Halvorsen, Tu Hoang
*/
package edu.uara.gui.custom;

import edu.uara.wrappers.CustomBorderGenerator;
import edu.uara.wrappers.CustomBorderGenerator.BorderLocation;
import java.awt.Color;
import javax.swing.JLabel;
import javax.swing.JSpinner;
import javax.swing.JTextField;
import javax.swing.SpinnerNumberModel;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

/**
 * Frame for choosing border colors and widths.
 * @author  paul
 */
public class BorderChooser extends javax.swing.JDialog implements ChangeListener {
    
    private CustomBorderGenerator customGen;
    private boolean okClick = false;

    /** Creates new form BorderChooser */
    public BorderChooser() {
        super((javax.swing.JFrame)null, true);
        initComponents();
    }
    
    public BorderChooser(CustomBorderGenerator cbg, Color bgc, Color fgc) {
        super((javax.swing.JFrame)null, true);

        initComponents();
        
        this.spnTop.setValue(cbg.getEdgeWidth(BorderLocation.Top));
        this.spnBottom.setValue(cbg.getEdgeWidth(BorderLocation.Bottom));
        this.spnLeft.setValue(cbg.getEdgeWidth(BorderLocation.Left));
        this.spnRight.setValue(cbg.getEdgeWidth(BorderLocation.Right));
        
        this.lblSample.setBorder(cbg.generateBorder());
        this.lblSample.setBackground(bgc);
        this.lblSample.setForeground(fgc);
        
        this.clrChooser.setColor(cbg.getEdgeColor(BorderLocation.Top));
        
        customGen = cbg;
        
        this.clrChooser.getSelectionModel().addChangeListener(this);
        this.spnTop.addChangeListener(this);
        this.spnBottom.addChangeListener(this);
        this.spnLeft.addChangeListener(this);
        this.spnRight.addChangeListener(this);
    }
    
    public CustomBorderGenerator getBorder() {
        return customGen;
    }
    
    public boolean isOk() {
        return this.okClick;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTop = new javax.swing.JLabel();
        lblLeft = new javax.swing.JLabel();
        lblRight = new javax.swing.JLabel();
        lblBottom = new javax.swing.JLabel();
        lblSample = new javax.swing.JLabel();
        clrChooser = new javax.swing.JColorChooser();
        btnOk = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        spnTop = new JSpinner(new SpinnerNumberModel(0, 0, 9, 1));
        spnRight = new JSpinner(new SpinnerNumberModel(0, 0, 9, 1));
        spnLeft = new JSpinner(new SpinnerNumberModel(0, 0, 9, 1));
        spnBottom = new JSpinner(new SpinnerNumberModel(0, 0, 9, 1));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblTop.setText("Top Width");

        lblLeft.setText("Left Width");

        lblRight.setText("Right Width");

        lblBottom.setText("Bottom Width");

        lblSample.setBackground(new java.awt.Color(255, 255, 255));
        lblSample.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSample.setText("Sample");

        btnOk.setText("OK");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(clrChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(86, 86, 86)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(44, 44, 44)
                                    .addComponent(lblLeft)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(spnLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(spnRight, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lblRight))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(157, 157, 157)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(spnTop, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblTop))))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(96, 96, 96)
                            .addComponent(lblSample, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(229, 229, 229)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBottom)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(spnBottom, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTop)
                .addGap(5, 5, 5)
                .addComponent(spnTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spnRight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spnLeft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLeft)
                    .addComponent(lblRight))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spnBottom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBottom)
                .addGap(21, 21, 21)
                .addComponent(clrChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSample, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOk)
                    .addComponent(btnCancel))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
    this.okClick = true;
    this.dispose();
}//GEN-LAST:event_btnOkActionPerformed

private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
    this.okClick = false;
    this.customGen = null;
    this.dispose();
}//GEN-LAST:event_btnCancelActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BorderChooser(new CustomBorderGenerator(1, 1, 1, 1, Color.blue), Color.white, Color.black).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnOk;
    private javax.swing.JColorChooser clrChooser;
    private javax.swing.JLabel lblBottom;
    private javax.swing.JLabel lblLeft;
    private javax.swing.JLabel lblRight;
    private javax.swing.JLabel lblSample;
    private javax.swing.JLabel lblTop;
    private javax.swing.JSpinner spnBottom;
    private javax.swing.JSpinner spnLeft;
    private javax.swing.JSpinner spnRight;
    private javax.swing.JSpinner spnTop;
    // End of variables declaration//GEN-END:variables

    
    public void stateChanged(ChangeEvent e) {
        this.customGen.setEdgeColor(BorderLocation.Top, this.clrChooser.getColor());
        this.customGen.setEdgeWidth(BorderLocation.Top, (Integer)this.spnTop.getValue());
        this.customGen.setEdgeWidth(BorderLocation.Bottom, (Integer)this.spnBottom.getValue());
        this.customGen.setEdgeWidth(BorderLocation.Left, (Integer)this.spnLeft.getValue());
        this.customGen.setEdgeWidth(BorderLocation.Right, (Integer)this.spnRight.getValue());
        
        this.lblSample.setBorder(this.customGen.generateBorder());
    }

}
